---
- name: create unbound log directory
  file:
    path: "{{ unbound_log_dir }}"
    state: directory
    owner: unbound
    group: unbound
    mode: 0750
  tags:
    - unbound
    - configure

- name: configure apparmor for unbound
  template:
    src: "etc/apparmor.d/local/usr.sbin.unbound.j2"
    dest: "/etc/apparmor.d/local/usr.sbin.unbound"
  notify: restart apparmor
  tags:
    - unbound
    - configure

- name: set default configuration
  template:
    src: "etc/unbound/global.conf.j2"
    dest: "{{ unbound_conf_dir }}/global.conf"
  notify: restart unbound
  tags:
    - unbound
    - configure

- name: configure local-data
  template:
    src: "etc/unbound/local-data.conf.j2"
    dest: "{{ unbound_conf_dir }}/{{ domain.name }}.conf"
  loop: >-
    {{
    (
      unbound_domain
    ) | flatten
    }}
  loop_control:
    loop_var: domain
    label: "{{ domain.name }}"
  notify: restart unbound
  tags:
    - unbound
    - domain
